---
- name: Install api-hour-demo on a server
  hosts:
        - api-hour.example.com
  gather_facts: True
  tasks:
        - name: Install packages on Debian
          apt: name={{item}} state=present
          when: ansible_os_family == 'Debian'
          with_items:
            - git

        - name: Install packages on CentOS
          yum: name={{item}} state=present
          when: ansible_os_family == 'RedHat'
          with_items:
            - git

        - name: Clone project
          git: repo=https://github.com/Eyepea/api-hour-demo dest=/opt/api-hour-demo

        - name: Install requirements
          pip: requirements=/opt/api-hour-demo/requirements.txt
               virtualenv=/opt/api-hour-demo/pyvenv
               virtualenv_command=/usr/local/pythonz/pythons/CPython-3.5.1/bin/pyvenv

        - name: Create log dir
          file: dest=/var/log/api-hour-demo owner=root group=root state=directory

        - name: Link default config file
          file: state=link dest=/etc/default/api-hour-demo src=/opt/api-hour-demo/etc/default/api-hour-demo

        - name: Link startup script
          file: state=link dest=/etc/init.d/api-hour-demo src=/opt/api-hour-demo/etc/init.d/api-hour-demo

        - name: Link logrotate config file
          file: state=link dest=/etc/logrotate.d/api-hour-demo src=/opt/api-hour-demo/etc/logrotate.d/api-hour-demo

        - name: Make it start with the system
          service: name=api-hour-demo enabled=yes

        - name: Copy the template configuration file to etc
          command: cp -a /opt/api-hour-demo/etc/api-hour-demo /etc/
          args:
            creates: "/etc/api-hour-demo"
